import type {
  DepositConfigResponse,
  SaleConfigResponse,
  SaleProgress,
  TmaDeposit,
  TmaSale,
  TrustLevelLadderResponse,
  UserProfileResponse,
  BalanceHistoryEntry,
} from './tma.interface.js';
import type { ReferralSummary } from './referral.interface.js';
import type { IncomeAnalyticsResponse } from './income-analytics.interface.js';
import type { FiatDepositOptionsResponse, TmaFiatDeposit } from './fiat-deposit.interface.js';

/** One sale of a demo account, as its status page asks for it. */
export interface TmaDemoSale {
  /** `GET /tma/sales/:id`. */
  readonly sale: TmaSale;
  /** `GET /tma/sales/:id/progress`. */
  readonly progress: SaleProgress;
}

/**
 * Everything a demo account's screens read, generated by the server and
 * delivered once, on `POST /tma/auth`.
 *
 * **Recorded answers, not a scenario.** Each field is the exact body the
 * endpoint named beside it would have returned, so the Mini App answers those
 * requests from here without the round trip — every request from a phone goes
 * over Tor to reach the origin, and a promoter recording the app should not
 * spend the video on spinners. What the app shows is therefore drawn by the
 * very components a real account's figures go through.
 *
 * **It never touches anything real.** No figure here is stored; the account's
 * own balance, history and referrals stay exactly what they are and the panel
 * shows those. The server refuses every write a demo account sends, so a
 * screen showing a balance that does not exist cannot spend it.
 *
 * Priced at the rates of the moment it was built. The two that move while the
 * app is open — the sale form's rate and the top-up offer's — are re-priced on
 * the device from the live poll, or the form would quote one rate beside a
 * dashboard showing another.
 */
export interface TmaDemoPack {
  /** `GET /tma/user/profile`. */
  readonly profile: UserProfileResponse;
  /** `GET /tma/user/balance-history`, newest first. */
  readonly history: readonly BalanceHistoryEntry[];
  /** `GET /tma/referral`. The code and the link are the account's real ones. */
  readonly referral: ReferralSummary;
  /** `GET /tma/analytics/income`. */
  readonly income: IncomeAnalyticsResponse;
  /** `GET /tma/trust-levels`. */
  readonly trustLadder: TrustLevelLadderResponse;
  /** `GET /tma/sales/config`, before the live rate is applied. */
  readonly saleConfig: SaleConfigResponse;
  /** `GET /tma/deposits/config`, before the live rate is applied. The wallet is the real one. */
  readonly depositConfig: DepositConfigResponse;
  /** `GET /tma/fiat-deposits/options`, before the live rate is applied. */
  readonly fiatOptions: FiatDepositOptionsResponse;
  /** Every sale on {@link history}, for its status page. */
  readonly sales: readonly TmaDemoSale[];
  /** Every crypto deposit on {@link history}, for its page. */
  readonly deposits: readonly TmaDeposit[];
  /** Every hryvnia top-up on {@link history}, for its page. */
  readonly fiatDeposits: readonly TmaFiatDeposit[];
  /**
   * The card a top-up started on the device shows as its recipient.
   *
   * **Deliberately not a valid card number** — it fails the Luhn check, so a
   * banking app refuses it outright. It is on screen in an advertisement, and
   * somebody watching will try to pay it: a number that happened to be a real
   * card would send a stranger's money to another stranger.
   */
  readonly recipientCard: string;
}
